### ISSUE TITLE
testing models

### ISSUE THREAD

**Issue by sonjageorgievska** [DeepRank/deeprank#122]
In NeuralNet.py, function test, the plotting is done only in case of regression, should be something like :

# do test
        self.data = {}
        _, self.data['test'] = self._epoch(loader,train_model=False)
        if self.task == 'reg':
            self._plot_scatter_reg(self.outdir+'/prediction.png')            
        else:
            self._plot_scatter(self.outdir+'/prediction.png')
        self.plot_hit_rate(self.outdir+'/hitrate.png')

**Comment by CunliangGeng** [comment]
Bug fixed on `development` branch. Close the issue now.
