### ISSUE TITLE
add torch.no_grad() to speed up the evaluation step

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#125]
We are not using `torch.no_grad()`. But it is recommended to use to speed up the evaluation step: https://discuss.pytorch.org/t/model-eval-vs-with-torch-no-grad/19615/7

**Comment by CunliangGeng** [comment]
Good point, will implement that to the code.

**Comment by CunliangGeng** [comment]
/remind test reminder, tell me in 2 minutes

**Comment by CunliangGeng** [comment]
Implemented in the commit f51c58d.
Close the issue now.
