### ISSUE TITLE
Dataset augmentation on the fly

### ISSUE THREAD

**Issue by NicoRenaud** [DeepRank/deeprank#15]
The augmentation of the data set is now done statically. We must generate extra conformation in the .hdf5 file by rotating the strucrure and mapping the features. This will lead to very large dataset. One option would be to augment the dataset on the fly during the training of the network. To do that we will have to rotate the feature and map them during the batch preparation. This can be done but might cost a lot of CPU time.

**Comment by sonjageorgievska** [comment]
Does it make sense to make the rotation on the GPU instead on the CPU?

**Comment by NicoRenaud** [comment]
the proteins are still relatively small (few thousands atoms) so I don't think we'll gain much from GPU. But I haven't tested it

**Comment by NicoRenaud** [comment]
There is a new branch issue25-mapfly that tries to do that
It's of course slower than reading precomputed data but it might be manageable

**Comment by NicoRenaud** [comment]
It's been in the developement branch for a bit now and it seems to work
