### ISSUE TITLE
1AK4 test pdb files were missing chainID, causing a warning to be rised in all test/tutorial scripts

### ISSUE THREAD

**Issue by DarioMarzella** [DeepRank/deeprank#191]
1AK4 files in `test/1AK4/decoys` are missing the chainID. 

This lead to the fact that everytime a user follows any tutorial that involves dataset preparation or runs a test scripts, will receive pointless warning messages reporting his files are missing chainID.

I have added chainIDs in doc_DM commit 313e3cd by using pdb_segxchain.

**Comment by CunliangGeng** [comment]
OK, it's fine, thanks.
