### ISSUE TITLE
chain IDs are hard coded as A and B in AtomicFeature.py

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#198]
In `AtomicFeature.py`:

```
            xyzA = np.array(self.sqldb.get('x,y,z', chainID='A'))
            xyzB = np.array(self.sqldb.get('x,y,z', chainID='B'))

            chargeA = np.array(self.sqldb.get('CHARGE', chainID='A'))
            chargeB = np.array(self.sqldb.get('CHARGE', chainID='B'))
```

**Comment by NicoRenaud** [comment]
That's a big change in the code. Plus from a user perspective it means that somehow we should be able to provide chain IDs in the  feature selector.

**Comment by LilySnow** [comment]
So do we want the users to change chain IDs of their models into A and B?

**Comment by CunliangGeng** [comment]
Let me have a look at the code.

**Comment by NicoRenaud** [comment]
Yes I agree we should check that and issue a proper warning/error message

**Comment by CunliangGeng** [comment]
@DarioMarzella Could you have a test on this [branch](https://github.com/DeepRank/deeprank/tree/issue198) with your own data to see if the flexible setting of chainIDs works well or not? Check `test_generate.py` and `test_learn.py` for how to set chainIDs.

You first need to install latest pdb2sql from this [branch](https://github.com/DeepRank/pdb2sql/tree/chainid).

**Comment by DarioMarzella** [comment]
> You need to install latest pdb2sql from this [branch](https://github.com/DeepRank/pdb2sql/tree/chainid) and retrain your model.

The branch you linked ("chainid') of pdb2sql raises a 404 error. Did you mean the [specify_chains](https://github.com/DeepRank/pdb2sql/tree/specify_chains) branch?

**Comment by CunliangGeng** [comment]
@DarioMarzella The updates of pdb2sql has been merged this morning, you should install it from master branch.

**Comment by DarioMarzella** [comment]
Daniel (the guy who came across the chainID issue as mentioned by Li) had it tested on his data and it worked. 
On the branch Issue198, I tested it as well with other chainID and it worked, so I guess this issue can be closed now. 
Thanks for fixing it.

**Comment by LilySnow** [comment]
Could you please modify the test cases and pssm files in the test folder so that unitest can test it?

**Comment by DarioMarzella** [comment]
In branch issue198 they have already been modified (from Cunliang I guess) to chain C and D (from A and B). 
Do you want me to write another test case with other chain IDs (or with other proteins)?

**Comment by LilySnow** [comment]
Perfect! No need to do more tests then :)
