### ISSUE TITLE
two minor issues with DataGenerator

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#25]
[the following issues are mentioned by Nico. I report here in case we forget.] 

When I use DataGenerator to add new target values (binary class) to an existing hdf5, I had the following two problems. 

1. If a hdf5 does not exist, DataGenerator(compute_targets='...') will generate an empty hdf5. No error reported. 
2. After the new target values are added to the hdf5 file, we cannot add it again. The code will throw the following errors:

> Traceback (most recent call last):
>   File "add_binaryClass.py", line 19, in <module>
>     data_set.add_target()
>   File "/home/lixue/deeprank/deeprank/deeprank/generate/DataGenerator.py", line 451, in add_target
>     self._compute_targets(self.compute_targets, molgrp['complex'].value,molgrp['targets'])
>   File "/home/lixue/deeprank/deeprank/deeprank/generate/DataGenerator.py", line 970, in _compute_targets
>     targ_module.__compute_target__(pdb_data,targrp)
>   File "/home/lixue/deeprank/deeprank/deeprank/targets/binary_class.py", line 21, in __compute_target__
>     targrp.create_dataset('BIN_CLASS',data=np.array(classID))
>   File "/home/lixue/softwares/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 111, in create_dataset
>     self[name] = dset
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/home/lixue/softwares/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 276, in __setitem__
>     h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5o.pyx", line 202, in h5py.h5o.link
> RuntimeError: Unable to create link (Name already exists)

My code add_binaryClass.py is here: /home/lixue/deeprank/BM4/test/add_binaryClass.py

**Comment by NicoRenaud** [comment]
I've tested the new code and it works. closing the issue
