### ISSUE TITLE
initialize the neural network with weights from a pretrained network

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#32]
The initialization of a nn is too random. So I would like to initialize it with reasonable weights from a pretrained model. 

The pretrained models are generated by: `torch.save(model.state_dict(), PATH)` (recommended by pytorch)

So far our code works with the entire model saved by `torch.save(model, PATH)`

**Comment by NicoRenaud** [comment]
How would you get the pretrained model ?
We can also initialize the weight with a given distribution ... I don't know what's best

**Comment by LilySnow** [comment]
The pretrained model can from other data, for example, the trained model from 3DeepFace project.

**Comment by NicoRenaud** [comment]
we can probably do that without adding anything to the `NeuralNet` class. I'm afraid we are adding to many options to it and it will get unmanageable

**Comment by NicoRenaud** [comment]
```python

model = NeuralNet( ..... )
model.net.load_state_dict(torch.load(PATH))
```
