### ISSUE TITLE
adding the NaivePSSM feature to the database does not work

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#33]
Data:
/projects/0/deeprank/PPI4DOCK/test

Code (test_generate.py under the same folder):
`database = DataGenerator(pdb_source=None,pdb_native=None,data_augmentation=None,
                                     pssm_source='./pssm',
                                     compute_features  = ['deeprank.features.NaivePSSM'], hdf5=h5)`

Error message:
> ======================================================================
> ERROR: test_4_add_feature (__main__.TestGenerateData)
> Add a feature to the database.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_generate.py", line 102, in test_4_add_feature
>     database.add_feature(prog_bar=True)
>   File "/nfs/home6/lixue1/deeprank/deeprank/generate/DataGenerator.py", line 368, in add_feature
>     self._compute_features(self.compute_features, molgrp['complex'].value,molgrp['features'],molgrp['features_raw'] )
>   File "/nfs/home6/lixue1/deeprank/deeprank/generate/DataGenerator.py", line 974, in _compute_features
>     feat_module.__compute_feature__(pdb_data,featgrp,featgrp_raw)
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/NaivePSSM.py", line 201, in __compute_feature__
>     pssm.read_PSSM_data()
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/NaivePSSM.py", line 83, in read_PSSM_data
>     raise FileNotFoundError('No PSSM file found for %s in %s',self.mol_name,self.pssm_path)
> FileNotFoundError: [Errno No PSSM file found for %s in %s] 2w83-AB_20: '/nfs/home6/lixue1/deeprank/deeprank/features/PSSM/'
> 
> ----------------------------------------------------------------------

According to Nico, the NativePSSM feature should be removed.

**Comment by NicoRenaud** [comment]
I'll remove the naive pssm it was just a guess work on my side
