### ISSUE TITLE
(semi)Bug: cannot add a feature that is already inside the hdf5 file

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#34]
When trying to add a feature to a hdf5 file, which already has this feature, we will get the following error message:

> ======================================================================
> ERROR: test_4_add_feature (__main__.TestGenerateData)
> Add a feature to the database.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_generate.py", line 102, in test_4_add_feature
>     database.add_feature(prog_bar=True)
>   File "/nfs/home6/lixue1/deeprank/deeprank/generate/DataGenerator.py", line 368, in add_feature
>     self._compute_features(self.compute_features, molgrp['complex'].value,molgrp['features'],molgrp['features_raw'] )
>   File "/nfs/home6/lixue1/deeprank/deeprank/generate/DataGenerator.py", line 974, in _compute_features
>     feat_module.__compute_feature__(pdb_data,featgrp,featgrp_raw)
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/FullPSSM.py", line 201, in __compute_feature__
>     pssm.export_dataxyz_hdf5(featgrp)
>   File "/nfs/home6/lixue1/deeprank/deeprank/features/FeatureClass.py", line 97, in export_dataxyz_hdf5
>     featgrp.create_dataset(name,data=ds)
>   File "/home/lixue1/tools/anaconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 119, in create_dataset
>     self[name] = dset
>   File "/home/lixue1/tools/anaconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 287, in __setitem__
>     h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5o.pyx", line 202, in h5py.h5o.link
> RuntimeError: Unable to create link (name already exists)
>
>----------------------------------------------------------------------

Code:

```
            database = DataGenerator(pdb_source=None,pdb_native=None,data_augmentation=None,
                                     pssm_source='./1AK4/pssm_new/',
                                     compute_features  = ['deeprank.features.FullPSSM'], hdf5=h5)
```

**Comment by NicoRenaud** [comment]
Should be fixed by now !
