### ISSUE TITLE
a minor bug of target_ordering in NeuralNet.py

### ISSUE THREAD

**Issue by CunliangGeng** [DeepRank/deeprank#38]
`self.target_ordering = target_ordering` is overrode by `self.process_dataset()` when process is True.

**Comment by NicoRenaud** [comment]
is that solve now ?

**Comment by CunliangGeng** [comment]
No, I have not touched it yet.

**Comment by NicoRenaud** [comment]
I don't get why that's a problem though ? If the selected target is in the lists the correct ordering is selected .... What would you like to have instead ?

**Comment by CunliangGeng** [comment]
Sorry, the bug is in the DataSet.py.
If the selected target is not in all lists, then the target_ordering will be set to `lower`.
The problem is if I have set the target_ordering line 135 `self.target_ordering = target_ordering`, e.g .  `higher`, then  line 142 `self.process_dataset()` will still reset it to `lower` if the `process` is True.

**Comment by NicoRenaud** [comment]
that's not exactly true. In `_get_target_ordering()` (line 629) that is called in `process_dataset()` the code tries to assess which ordering it is. It only defaults to `lower` in case the target ordering is not defined no ?

**Comment by CunliangGeng** [comment]
No. Whether the target ordering is defined or not (in line 135 self.target_ordering = target_ordering), the self.process_dataset() will reset the value. It could be a  problem when it is defined as `higher` or `None`  but reset to default `lower`.

**Comment by NicoRenaud** [comment]
I don't see that in the code though 
```

    def _get_target_ordering(self):
        """Determine if ordering of the target.
        This can be lower the better or higher the better
        If it can't determine the ordering 'lower' is assumed
        """

        lower_list = ['IRMSD','LRMSD','HADDOCK']
        higher_list = ['DOCKQ','Fnat']
        NA_list = ['binary_class','BIN_CLASS', 'class']

        if self.select_target in lower_list:
            self.target_ordering = 'lower'
        elif self.select_target in higher_list:
            self.target_ordering = 'higher'
        elif self.select_target in NA_list:
            self.target_ordering = None
        else:
            print('  Target ordering unidentified. lower assumed')
            self.target_ordering = 'lower'
```

**Comment by NicoRenaud** [comment]
Am I missing something ?
