### ISSUE TITLE
How to best normalize the features ?

### ISSUE THREAD

**Issue by NicoRenaud** [DeepRank/deeprank#47]
At the moment each channel is normalized  so that the distribution of all the values of each channel for all the conformations are Gaussian distributed with mean 0 and std 1. Is it what we want considering that we have some features that are physically positive and negative ? 

For example a conformation that would lead to only positive Coulomb interaction (very bad conformation ) could have pos/neg values after normalization. Same for a conf with only negative coulomb interaction (much better conformation) could have pos/neg values after normalization ..... That doesn't sound right to me 

Plus doing the statistic over the entire dataset takes for ever 

Should we normalize at all ?

**Comment by LilySnow** [comment]
Based on our iscore experience, we should normalize the features within a case. That is, we should calculate median and IQR from the models from one docking case and normalize the features. We can also use mean and std for the normalization. So far, median and IQR give the best results.

**Comment by NicoRenaud** [comment]
So now we normalize the features by calculating the mean and std of every channel over the entire dataset. We then transform the feature values by retracting the mean and dividing by the std. That leads to a distribution centered around 0 and with a std of 1

**Comment by NicoRenaud** [comment]
When the features are directly stored in the hdf5 the mean value and std of each channel are stored in a separate pickle file as a dict.  We could change the file format so that it;s in the hdf5 directly. But that's a lot of work for no real good reasons

**Comment by NicoRenaud** [comment]
When we map on the fly the cost of computing the normalization factor is roughly equivalent to one full epoch. So that's manageable

**Comment by sonjageorgievska** [comment]
I use batch normalization before the first layer, also inside
