### ISSUE TITLE
the development` branch is broken on classification

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#58]
Error message:

> Traceback (most recent call last):
>   File "learn.py", line 44, in <module>
>     model.train(nepoch = 5, divide_trainset = None, train_batch_size = 5, num_workers=0, save_model='all')
>   File "/nfs/home6/lixue1/deeprank/deeprank/learn/NeuralNet.py", line 336, in train
>     save_model=save_model)
>   File "/nfs/home6/lixue1/deeprank/deeprank/learn/NeuralNet.py", line 596, in _train
>     self.valid_loss,self.data['valid'] = self._epoch(valid_loader,train_model=False)
>   File "/nfs/home6/lixue1/deeprank/deeprank/learn/NeuralNet.py", line 763, in _epoch
>     data['hit'] = self._get_relevance(data)
>   File "/nfs/home6/lixue1/deeprank/deeprank/learn/NeuralNet.py", line 1084, in _get_relevance
>     out = F.softmax(torch.FloatTensor(out), dim=1).data.numpy()[:,1]
> IndexError: index 1 is out of bounds for axis 1 with size 1

**Comment by CunliangGeng** [comment]
Code is fixed.

Do not forget to use `from deeprank.learn.model3d import cnn_class as cnn3d` for classification
