### ISSUE TITLE
no proper warning when pssm is not matched with the pdb file

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#61]
When a pssm file does not match the pdb file, no proper warning is generated.

**Comment by NicoRenaud** [comment]
Did you have that problem ? The assumption was that the PSSM would be generated with Cunliang's code and therefore would match the PDB. But in any case we should indeed issue a warning or an error.

**Comment by LilySnow** [comment]
Another related problem. When pssm file does not contain the contact residue, no error is reported. This is the case in the `example` of 1AK4. Chain B has residue 147 (a contact residue of `1AK4_1w.pdb`), and the pssm file does not have this residue, but error is reported.
