### ISSUE TITLE
shall we try to use informative variable names?

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#8]
Shall we try to use informative variable names for better team work, like k, v, kk, vv below?

>       def _export_epoch_hdf5(self,epoch,data):
>           """Export the epoch data to the hdf5 file
> 
>           Args:
>               epoch (int): index of the epoch
>               data (dict): data of the epoch
>           """
>           grp_name = 'epoch_%04d' %epoch
>           grp = self.f5.create_group(grp_name)
>           grp.attrs['type'] = 'epoch'
>             for k,v in data.items():
>               try:
>                   sg = grp.create_group(k)
>                     for kk,vv in v.items():

**Comment by NicoRenaud** [comment]
fixed I'm closing that issue
