### ISSUE TITLE
we should plot performance plots after (not before) one epoch/mini-batch

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#84]
Currently, we are plotting performance before one epoch. For example, if I run the training for one epoch only, the plots generated are totally random because it is plotting the performance before the training. 

Each epoch is taking ~12 days. Using our current plot, we are wasting one epoch time.

**Comment by sonjageorgievska** [comment]
The plots were not random, but the training curve was always one epoch ahead. It is fixed now.
