### ISSUE TITLE
Run the test suite on deeprank and got a deprecationwaring

### ISSUE THREAD

**Issue by MelodyLin0731** [DeepRank/deeprank#85]
I tried to run the test file on deeprank, and however, I got a deprecationwaring as below:
DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index confusion[t][r[1]>0.5]+=1

![deeprank01](https://user-images.githubusercontent.com/52483643/60569596-505c4d80-9da2-11e9-977f-21d113520967.jpg)

![deeprank02](https://user-images.githubusercontent.com/52483643/60569620-5b16e280-9da2-11e9-8a80-e5eefe882e14.jpg)

Is there anyone know how to solve this problem?

**Comment by CunliangGeng** [comment]
Hi there, 

Thank you for posting this issue.

The variable `confusion` is actually not used in the code after line 951 in `NeuralNet.py`. So you could simply ignore this problem.

To solve this warning, just do not use `np_bool` as an index of list.  Changing `r[1]>0.5` to `bool(r[1]>0.5)` will work. 

We'll update this piece of code soon.
